In [137]:
from sqlalchemy import create_engine 
import pymysql.cursors
import os

In [138]:
pw = os.getenv('MySQL_Pass')

In [139]:
connection_string = 'mysql+pymysql://root:' + pw + '@localhost:3306/'
engine = create_engine(connection_string)

In [435]:
pl_season2 = 2022

In [436]:
df = pd.read_csv(f"../data/{pl_season2}-{pl_season2-1999}/gws/merged_gw.csv")

In [437]:
id_df = pd.read_csv(f"../data/{pl_season2}-{pl_season2-1999}/player_idlist.csv")

In [438]:
name_list = []
for x in df['name']:
    name_list.append(x)

In [439]:
id_name = []
for x in range(0,len(id_df)):
    id_name.append(f"{id_df['first_name'][x] + ' ' + id_df['second_name'][x]}")

In [440]:
id_name

['Granit Xhaka',
 'Mohamed Elneny',
 'Rob Holding',
 'Thomas Partey',
 'Martin Ødegaard',
 'Kieran Tierney',
 'Nicolas Pépé',
 'Benjamin White',
 'Eddie Nketiah',
 'Emile Smith Rowe',
 'Bukayo Saka',
 'Takehiro Tomiyasu',
 'Aaron Ramsdale',
 'Gabriel dos Santos Magalhães',
 'Nuno Varela Tavares',
 'Gabriel Martinelli Silva',
 'Pablo Marí Villar',
 'Lucas Torreira di Pascua',
 'Reiss Nelson',
 'Matt Turner',
 'Fábio Ferreira Vieira',
 'William Saliba',
 'Marcus Oliveira Alencar',
 'Gabriel Fernando de Jesus',
 'Leandro Trossard',
 'Jorge Luiz Frello Filho',
 'Oleksandr Zinchenko',
 'Matthew Smith',
 'Ethan Nwaneri',
 'Lino Sousa',
 'Karl Hein',
 'Amario Cozier-Duberry',
 'Nathan Butler-Oyedeji',
 'Jakub Kiwior',
 'Reuell Walters',
 'Mauro Bandeira',
 'Philippe Coutinho Correia',
 'Emiliano Martínez Romero',
 'Calum Chambers',
 'Lucas Digne',
 'Bertrand Traoré',
 'Robin Olsen',
 'Morgan Sanson',
 'John McGinn',
 'Kortney Hause',
 'Tyrone Mings',
 'Ollie Watkins',
 'Marvelous Nakamba',
 'Emiliano Buendía Stati',
 'Matty Cash',
 'Ezri Konsa Ngoyo',
 'Leon Bailey',
 'Douglas Luiz Soares de Paulo',
 'Jacob Ramsey',
 'Tim Iroegbunam',
 'Diego Carlos Santos Silva',
 'Anwar El Ghazi',
 'Keinan Davis',
 'Boubacar Kamara',
 'Cameron Archer',
 'Jaden Philogene-Bidace',
 'Frédéric Guilbert',
 'Leander Dendoncker',
 'Ludwig Augustinsson',
 'Kaine Kesler Hayden',
 'Ashley Young',
 'Lamare Bogarde',
 'Filip Marschall',
 'Kadan Young',
 'Alexandre Moreno Lopera',
 'Viljami Sinisalo',
 'Jhon Durán',
 'Sil Swinkels',
 'Oliwier Zych',
 'James Wright',
 'Sebastian Revan',
 'Travis Patterson',
 "Tommi O'Reilly",
 'Adam Smith',
 'Junior Stanislas',
 'Ryan Fredericks',
 'David Brooks',
 'Jamal Lowe',
 'Kieffer Moore',
 'Emiliano Marcondes',
 'Jefferson Lerma Solís',
 'Jack Stacey',
 'Dominic Solanke',
 'Lewis Cook',
 'Ben Pearson',
 'Ryan Christie',
 'Philip Billing',
 'Chris Mepham',
 'Mark Travers',
 'Lloyd Kelly',
 'Siriki Dembélé',
 'Jaidon Anthony',
 'Jordan Zemura',
 'Will Dennis',
 'Jack Stephens',
 'Joe Rothwell',
 'Marcus Tavernier',
 'James Hill',
 'Darren Randolph',
 'Norberto Murara Neto',
 'Marcos Senesi',
 'Christian Saydee',
 'Owen Bevan',
 'Cameron Plain',
 'Daniel Adu-Adjei',
 'Michael Dacosta Gonzalez',
 'Dominic Sadi',
 'Dango Ouattara',
 'Euan Pollock',
 'Antoine Semenyo',
 'Matías Viña',
 'Illia Zabarnyi',
 'Hamed Traorè',
 'Ben Greenwood',
 'Max Kinsey-Wellings',
 'Pontus Jansson',
 'Christian Nørgaard',
 'Ivan Toney',
 'David Raya Martin',
 'Sergi Canós Tenés',
 'Josh Dasilva',
 'Kristoffer Ajer',
 'Rico Henry',
 'Vitaly Janelt',
 'Saman Ghoddos',
 'Mathias Jensen',
 'Yoane Wissa',
 'Mads Roerslev Rasmussen',
 'Mads Bech Sørensen',
 'Ethan Pinnock',
 'Frank Onyeka',
 'Shandon Baptiste',
 'Bryan Mbeumo',
 'Charlie Goode',
 'Marcus Forss',
 'Dominic Thompson',
 'Mads Bidstrup',
 'Ellery Balcombe',
 'Aaron Hickey',
 'Keane Lewis-Potter',
 'Thomas Strakosha',
 'Ben Mee',
 'Fin Stevens',
 'Halil Dervişoğlu',
 'Mikkel Damsgaard',
 'Mathias Jorgensen',
 'Ryan Trevitt',
 'Matthew Cox',
 'Tristan Crama',
 'Yegor Yarmolyuk',
 'Kevin Schade',
 'Michael Olakigbe',
 'Adam Lallana',
 'Jason Steele',
 'Danny Welbeck',
 'Pascal Groß',
 'Lewis Dunk',
 'Solly March',
 'Adam Webster',
 'Joël Veltman',
 'Robert Sánchez',
 'Tariq Lamptey',
 'Steven Alzate',
 'Alexis Mac Allister',
 'Jakub Moder',
 'Enock Mwepu',
 'Jeremy Sarmiento Morante',
 'Moisés Caicedo Corozo',
 'Taylor Richards',
 'Haydon Roberts',
 'Deniz Undav',
 'Kaoru Mitoma',
 'Julio Enciso',
 'Kacper Kozłowski',
 'Billy Gilmour',
 'Kjell Scherpen',
 'Matt Clarke',
 'Jan Paul van Hecke',
 'Levi Colwill',
 'Pervis Estupiñán',
 'Evan Ferguson',
 'Ed Turns',
 'Andrew Moran',
 'James Furlong',
 'Jack Hinshelwood',
 'Facundo Buonanotte',
 'Yasin Ayari',
 'Odeluga Offiah',
 'Tom McGill',
 'Cameron Peupion',
 'Imari Samuels',
 'Carney Chukwuemeka',
 'Marc Cucurella Saseta',
 'César Azpilicueta',
 'Thiago Emiliano da Silva',
 'Marcos Alonso',
 'Ross Barkley',
 'Mateo Kovacic',
 'Kepa Arrizabalaga',
 "N'Golo Kanté",
 'Hakim Ziyech',
 'Ruben Loftus-Cheek',
 'Timo Werner',
 'Robert Kenedy Nunes do Nascimento',
 'Ben Chilwell',
 'Christian Pulisic',
 'Trevoh Chalobah',
 'Mason Mount',
 'Malang Sarr',
 'Callum Hudson-Odoi',
 'Kai Havertz',
 'Reece James',
 'Edouard Mendy',
 'Conor Gallagher',
 'Armando Broja',
 'Ethan Ampadu',
 'Wesley Fofana',
 'Raheem Sterling',
 'Kalidou Koulibaly',
 'Harvey Vale',
 'Denis Zakaria',
 'Pierre-Emerick Aubameyang',
 'Marcus Bettinelli',
 'Omari Hutchinson',
 'Lewis Hall',
 'Bashir Humphreys',
 'David Datro Fofana',
 'Benoît Badiashile',
 'João Félix Sequeira',
 'Mykhailo Mudryk',
 'Andrey Nascimento dos Santos',
 'Noni Madueke',
 'Enzo Fernández',
 'Ethan Wady',
 'Alfie Gilchrist',
 'Albert Sambi Lokonga',
 'Vicente Guaita',
 'James Tomkins',
 'James McArthur',
 'Christian Benteke',
 'Joel Ward',
 'Nathaniel Clyne',
 'Luka Milivojevic',
 'Jordan Ayew',
 'Wilfried Zaha',
 'Jeffrey Schlupp',
 'Will Hughes',
 'Jairo Riedewald',
 'Joachim Andersen',
 'Odsonne Edouard',
 'Marc Guéhi',
 'Jean-Philippe Mateta',
 'Eberechi Eze',
 'Tyrick Mitchell',
 'Michael Olise',
 'Jesurun Rak-Sakyi',
 'Malcolm Ebiowei',
 'Nathan Ferguson',
 'Sam Johnstone',
 'Remi Matthews',
 'Luke Plange',
 'Cheick Doucouré',
 'Chris Richards',
 'Joseph Whitworth',
 'Kaden Rodney',
 'Killian Phillips',
 'John-Kymani Gordon',
 'Kofi Balmer',
 'Owen Goodman',
 'Jack Wells-Morrison',
 'David Ozoh',
 'Naouirou Ahamada',
 'Tayo Adaramola',
 'Neal Maupay',
 'Asmir Begović',
 'Salomón Rondón',
 'Seamus Coleman',
 'Andros Townsend',
 'Michael Keane',
 'Dele Alli',
 'Jordan Pickford',
 'Allan Marques Loureiro',
 'André Tavares Gomes',
 'Abdoulaye Doucouré',
 'Alex Iwobi',
 'Jean-Philippe Gbamin',
 'Yerry Mina',
 'Demarai Gray',
 'Tom Davies',
 'Dominic Calvert-Lewin',
 'Mason Holgate',
 'Ben Godfrey',
 'Vitalii Mykolenko',
 'Jarrad Branthwaite',
 'Nathan Patterson',
 'Niels Nkounkou',
 'James Tarkowski',
 'Conor Coady',
 'Rúben Nascimento Vinagre',
 'Dwight McNeil',
 'Stanley Mills',
 'Lewis Warrington',
 'James Garner',
 'Amadou Onana',
 'Reece Welch',
 'Idrissa Gueye',
 'Eldin Jakupovic',
 'Kyle John',
 'Thomas Cannon',
 'Isaac Price',
 'Ellis Simms',
 'Ishé Samuels-Smith',
 'Andy Lonergan',
 'Sean McAllister',
 'Cédric Alves Soares',
 'Bernd Leno',
 'Shane Duffy',
 'Tom Cairney',
 'Tim Ream',
 'Anthony Knockaert',
 'Nathaniel Chalobah',
 'Neeskens Kebano',
 'Bobby De Cordova-Reid',
 'Joe Bryan',
 'Paulo Gazzaniga Farias',
 'Terence Kongolo',
 'Tosin Adarabioyo',
 'Aleksandar Mitrović',
 'Harrison Reed',
 'Harry Wilson',
 'Marek Rodák',
 'Ivan Neves Abreu Cavaleiro',
 'Kenny Tete',
 'Josh Onomah',
 'Antonee Robinson',
 'Rodrigo Muniz Carvalho',
 'Jay Stansfield',
 'João Palhinha Gonçalves',
 'Daniel James',
 'Andreas Hoelgebaum Pereira',
 'Issa Diop',
 'Tyrese Francois',
 'Kevin Mbabu',
 'Luke Harris',
 'Manor Solomon',
 'Terry Ablade',
 'Layvin Kurzawa',
 'Willian Borges da Silva',
 'Carlos Vinícius Alves Morais',
 'Stefan Parkes',
 'Martial Godo',
 'Kristian Sekularac',
 'Sasa Lukic',
 'George Wickens',
 'Charlie Robinson',
 'Matthew Dibley-Dias',
 'Kasper Schmeichel',
 'Jonny Evans',
 'Ryan Bertrand',
 'Marc Albrighton',
 'Nampalys Mendy',
 'Jannik Vestergaard',
 'Danny Ward',
 'Jamie Vardy',
 'Ricardo Barbosa Pereira',
 'Daniel Amartey',
 'Timothy Castagne',
 'Youri Tielemans',
 'Ayoze Pérez',
 'James Maddison',
 'Kelechi Iheanacho',
 'Hamza Choudhury',
 'Harvey Barnes',
 'Wilfred Ndidi',
 'Kiernan Dewsbury-Hall',
 'Çaglar Söyüncü',
 'James Justin',
 'Boubakary Soumaré',
 'Luke Thomas',
 'Patson Daka',
 'Lewis Brunt',
 'Daniel Iversen',
 'Dennis Praet',
 'Alex Smithies',
 'Wout Faes',
 'Sammy Braybrooke',
 'Joe Wormleighton',
 'Kasey McAteer',
 'Victor Kristiansen',
 'Mateus Cardoso Lemos Martins',
 'Harry Souttar',
 'Wanya Marçal-Madivadua',
 'Liam Cooper',
 'Luke Ayling',
 'Mateusz Klich',
 'Adam Forshaw',
 'Rodrigo Moreno',
 'Stuart Dallas',
 'Patrick Bamford',
 'Diego Llorente',
 'Tyler Roberts',
 'Robin Koch',
 'Raphael Dias Belloli',
 'Jack Harrison',
 'Jamie Shackleton',
 'Pascal Struijk',
 'Kristoffer Klaesson',
 'Sam Greenwood',
 'Illan Meslier',
 'Junior Firpo Adames',
 'Crysencio Summerville',
 'Lewis Bate',
 'Joe Gelhardt',
 'Leo Fuhr Hjelde',
 'Rasmus Kristensen',
 'Marc Roca Junqué',
 'Brenden Aaronson',
 'Darko Gyabi',
 'Tyler Adams',
 'Luis Sinisterra Lucumí',
 'Cody Drameh',
 'Archie Gray',
 'Joel Robles',
 'Wilfried Gnonto',
 'Mateo Joseph Fernández',
 'Sonny Perkins',
 'Maximilian Wöber',
 'Georginio Rutter',
 'Weston McKennie',
 'Jeremiah Chilokoa-Mullen',
 'Diogo Pinheiro Monteiro',
 'James Milner',
 'Jordan Henderson',
 'Joel Matip',
 'Thiago Alcántara do Nascimento',
 'Alex Oxlade-Chamberlain',
 'Roberto Firmino',
 'Virgil van Dijk',
 'Alisson Ramses Becker',
 'Fabio Henrique Tavares',
 'Mohamed Salah',
 'Andrew Robertson',
 'Trent Alexander-Arnold',
 'Joseph Gomez',
 'Naby Keita',
 'Diogo Teixeira da Silva',
 'Caoimhin Kelleher',
 'Ibrahima Konaté',
 'Curtis Jones',
 'Konstantinos Tsimikas',
 'Luis Díaz',
 'Harvey Elliott',
 'Fábio Freitas Gouveia Carvalho',
 'Darwin Núñez Ribeiro',
 'Calvin Ramsay',
 'Adrián San Miguel del Castillo',
 'Rhys Williams',
 'Ben Davies',
 'Sepp van den Berg',
 'Nathaniel Phillips',
 'Luke Chambers',
 'Stefan Bajcetic',
 'Bobby Clark',
 'Harvey Davies',
 'Arthur Henrique Ramos de Oliveira Melo',
 'Ben Doak',
 'Cody Gakpo',
 'Kyle Walker',
 'Ilkay Gündogan',
 'Kevin De Bruyne',
 'John Stones',
 'Riyad Mahrez',
 'Jack Grealish',
 'João Cancelo',
 'Ederson Santana de Moraes',
 'Nathan Aké',
 'Aymeric Laporte',
 'Zack Steffen',
 'Bernardo Veiga de Carvalho e Silva',
 'Rúben Gato Alves Dias',
 'Phil Foden',
 'Rodrigo Hernandez',
 'Cole Palmer',
 'James McAtee',
 'Erling Haaland',
 'Julián Álvarez',
 'Luke Mbete-Tabu',
 'Josh Wilson-Esbrand',
 'Liam Delap',
 'Stefan Ortega Moreno',
 'Kalvin Phillips',
 'Scott Carson',
 'Rico Lewis',
 'Sergio Gómez',
 'Claudio Gomes',
 'Ben Knight',
 'Manuel Akanji',
 'Máximo Perrone',
 'Alex Robertson',
 'Shea Charles',
 "Nico O'Reilly",
 'Jack Butland',
 'Cristiano Ronaldo dos Santos Aveiro',
 'David De Gea Quintana',
 'Phil Jones',
 'Raphaël Varane',
 'Harry Maguire',
 'Frederico Rodrigues de Paula Santos',
 'Luke Shaw',
 'Bruno Borges Fernandes',
 'Alex Telles',
 'Marcus Rashford',
 'Donny van de Beek',
 'Victor Lindelöf',
 'Scott McTominay',
 'Eric Bailly',
 'Jadon Sancho',
 'Aaron Wan-Bissaka',
 'Diogo Dalot Teixeira',
 'Brandon Williams',
 'Anthony Elanga',
 'Anthony Martial',
 'Facundo Pellistri Rebollo',
 'Tom Heaton',
 'Tyrell Malacia',
 'Christian Eriksen',
 'Lisandro Martínez',
 'Amad Diallo',
 'Zidane Iqbal',
 'Alejandro Garnacho',
 'Carlos Henrique Casimiro',
 'Antony Matheus dos Santos',
 'Matej Kovár',
 'Kobbie Mainoo',
 'Nathan Bishop',
 'Shola Shoretire',
 'Rhys Bennett',
 'Wout Weghorst',
 'Marcel Sabitzer',
 'Marc Jurado Gomez',
 'Anthony Gordon',
 'Matt Ritchie',
 'Federico Fernández',
 'Ciaran Clark',
 'Karl Darlow',
 'Martin Dubravka',
 'Callum Wilson',
 'Kieran Trippier',
 'Dan Burn',
 'Ryan Fraser',
 'Jamaal Lascelles',
 'Dwight Gayle',
 'Paul Dummett',
 'Javier Manquillo Gaitán',
 'Emil Krafth',
 'Jacob Murphy',
 'Fabian Schär',
 'Matt Targett',
 'Allan Saint-Maximin',
 'Miguel Almirón Rejala',
 'Sean Longstaff',
 'Joelinton Cássio Apolinário de Lira',
 'Jamal Lewis',
 'Joe Willock',
 'Bruno Guimarães Rodriguez Moura',
 'Jeff Hendrick',
 'Nick Pope',
 'Sven Botman',
 'Elliot Anderson',
 'Harrison Ashby',
 'Alexander Isak',
 'Loris Karius',
 'Garang Kuol',
 'Lewis Miley',
 'Mark Gillespie',
 'Neco Williams',
 'Jonjo Shelvey',
 'Chris Wood',
 'Harry Arter',
 'Steve Cook',
 'Lyle Taylor',
 'Jack Colback',
 'Brice Samba',
 'Carlos Ribeiro Dias',
 'Joe Lolley',
 'Scott McKenna',
 'Mohamed Dräger',
 'Ryan Yates',
 'Joe Worrall',
 'Jonathan Panzo',
 'Xande Nascimento da Costa Silva',
 'Sam Surridge',
 'Richie Laryea',
 'Loïc Mbe Soh',
 'Brennan Johnson',
 'Alex Mighten',
 'Braian Ojeda Rodríguez',
 'Taiwo Awoniyi',
 'Dean Henderson',
 'Giulian Biancone',
 'Willy Boly',
 'Morgan Gibbs-White',
 'Moussa Niakhaté',
 'Omar Richards',
 'Wayne Hennessey',
 'Harry Toffolo',
 "Lewis O'Brien",
 'Jesse Lingard',
 'Orel Mangala',
 'Oliver Hammond',
 'Remo Freuler',
 'Cheikhou Kouyaté',
 'Emmanuel Dennis',
 'Renan Augusto Lodi dos Santos',
 'Loïc Badé',
 'Serge Aurier',
 'Dale Taylor',
 'Jordan Smith',
 'Gustavo Henrique Furtado Scarpa',
 'Danilo dos Santos de Oliveira',
 'Keylor Navas',
 'Felipe Augusto de Almeida Monteiro',
 'André Ayew',
 'George Shelvey',
 'Ainsley Maitland-Niles',
 'Roméo Lavia',
 'Theo Walcott',
 'Alex McCarthy',
 'Oriol Romeu Vidal',
 'Nathan Redmond',
 'Stuart Armstrong',
 'Mohamed Elyounoussi',
 'James Ward-Prowse',
 'Adam Armstrong',
 'Kyle Walker-Peters',
 'Jan Bednarek',
 'Che Adams',
 'Nathan Tella',
 'Lyanco Silveira Neves Vojnovic',
 'Yan Valery',
 'Will Smallbone',
 'Ibrahima Diallo',
 'Romain Perraud',
 'Moussa Djenepo',
 'Tino Livramento',
 'Mohammed Salisu',
 'Mateusz Lis',
 'Gavin Bazunu',
 'Armel Bella-Kotchap',
 'Willy Caballero',
 'Joe Ayodele-Aribo',
 'Sékou Mara',
 'Juan Larios López',
 'Duje Caleta-Car',
 'Samuel Edozie',
 'Lewis Payne',
 'Ryan Finnigan',
 'Jimmy Morgan',
 'Mislav Orsic',
 'Carlos Alcaraz',
 'James Bree',
 'Kamaldeen Sulemana',
 'Paul Onuachu',
 'Kamari Doyle',
 'Dominic Ballard',
 'Samuel Amo-Ameyaw',
 'Hugo Lloris',
 'Fraser Forster',
 'Harry Kane',
 'Son Heung-min',
 'Matt Doherty',
 'Eric Dier',
 'Lucas Rodrigues Moura da Silva',
 'Ben Davies',
 'Pierre-Emile Højbjerg',
 'Harry Winks',
 'Davinson Sánchez',
 'Ryan Sessegnon',
 'Steven Bergwijn',
 'Sergio Reguilón',
 'Japhet Tanganga',
 'Rodrigo Bentancur',
 'Oliver Skipp',
 'Joe Rodon',
 'Cristian Romero',
 'Yves Bissouma',
 'Emerson Leite de Souza Junior',
 'Dejan Kulusevski',
 'Dane Scarlett',
 'Ivan Perišić',
 'Harvey White',
 'Pape Matar Sarr',
 'Brandon Austin',
 'Alfie Devine',
 'Troy Parrott',
 'Richarlison de Andrade',
 'Clément Lenglet',
 'Djed Spence',
 'Bryan Gil Salvatierra',
 'Arnaut Danjuma',
 'Pedro Porro',
 'Romaine Mundle',
 'George Abbott',
 'Matthew Craig',
 'Yago de Santiago Alonso',
 'Danny Ings',
 'Lukasz Fabianski',
 'Angelo Ogbonna',
 'Aaron Cresswell',
 'Michail Antonio',
 'Manuel Lanzini',
 'Kurt Zouma',
 'Arthur Masuaku',
 'Vladimir Coufal',
 'Saïd Benrahma',
 'Jarrod Bowen',
 'Nikola Vlasic',
 'Declan Rice',
 'Tomas Soucek',
 'Pablo Fornals Malla',
 'Ben Johnson',
 'Nayef Aguerd',
 'Alphonse Areola',
 'Flynn Downes',
 'Gianluca Scamacca',
 'Emerson Palmieri dos Santos',
 'Conor Coventry',
 'Armstrong Oko-Flex',
 'Maxwel Cornet',
 'Thilo Kehrer',
 'Lucas Tolentino Coelho de Lima',
 'Divin Mubama',
 'Joseph Anang',
 'Krisztián Hegyi',
 'Kaelan Casey',
 'Craig Dawson',
 'Raúl Jiménez',
 'Jonathan Castro Otto',
 'José Malheiro de Sá',
 'Rúben da Silva Neves',
 'Hwang Hee-chan',
 'Nélson Cabral Semedo',
 'Daniel Castelo Podence',
 'Max Kilman',
 'Luke Cundle',
 'Pedro Lomba Neto',
 'Rayan Aït-Nouri',
 'Fabio Silva',
 'Toti António Gomes',
 'Francisco Jorge Tomás Oliveira',
 'Adama Traoré Diarra',
 'Matija Šarkić',
 'Yerson Mosquera Valdelamar',
 'João Filipe Iria Santos Moutinho',
 'Nathan Collins',
 'Jackson Smith',
 'Hugo Bueno López',
 'Joseph Hodge',
 'Connor Ronan',
 'Chem Campbell',
 'Gonçalo Manuel Ganchinho Guedes',
 'Matheus Luiz Nunes',
 'Sasa Kalajdzic',
 'Diego Da Silva Costa',
 'Boubacar Traoré',
 'Nathan Fraser',
 'Harvey Griffiths',
 'Dexter Lembikisa',
 'Matheus Santos Carneiro Da Cunha',
 'Mario Lemina',
 'Pablo Sarabia',
 'Daniel Bentley',
 'João Victor Gomes da Silva']

In [441]:
id_df['name'] = id_name

In [388]:
# df = df.drop(columns= 'id')

In [442]:
df = df.merge(id_df, on='name', how= 'left')

In [443]:
df = df.drop(columns= ['first_name', 'second_name',])

In [444]:
df.head(20)

,name,position,team,xP,assists,bonus,bps,clean_sheets,creativity,element,...,threat,total_points,transfers_balance,transfers_in,transfers_out,value,was_home,yellow_cards,GW,id
0,Nathan Redmond,MID,Southampton,1.5,0,0,3,0,0.0,403,...,0.0,1,0,0,0,55,False,0,1,403
1,Junior Stanislas,MID,Bournemouth,1.1,0,0,3,0,0.0,58,...,0.0,1,0,0,0,50,True,0,1,58
2,Armando Broja,FWD,Chelsea,2.0,0,0,3,0,0.3,150,...,19.0,1,0,0,0,55,False,0,1,150
3,Fabian Schär,DEF,Newcastle,2.4,0,3,43,1,14.6,366,...,25.0,15,0,0,0,45,True,0,1,366
4,Jonny Evans,DEF,Leicester,1.9,0,0,15,0,1.3,249,...,0.0,1,0,0,0,45,True,0,1,249
5,Brennan Johnson,FWD,Nott'm Forest,1.3,0,0,3,0,0.9,394,...,6.0,2,0,0,0,60,False,0,1,394
6,Cheick Doucouré,MID,Crystal Palace,1.1,0,0,16,0,3.8,514,...,0.0,2,0,0,0,50,True,0,1,514
7,Oliver Hammond,MID,Nott'm Forest,0.5,0,0,0,0,0.0,553,...,0.0,0,0,0,0,45,False,0,1,553
8,Luke Cundle,MID,Wolves,1.5,0,0,0,0,0.0,485,...,0.0,0,0,0,0,45,False,0,1,485
9,Fin Stevens,DEF,Brentford,1.0,0,0,0,0,0.0,540,...,0.0,0,0,0,0,40,False,0,1,540
10,Brandon Austin,GK,Spurs,1.5,0,0,0,0,0.0,451,...,0.0,0,0,0,0,40,True,0,1,451
11,Luka Milivojevic,MID,Crystal Palace,0.5,0,0,3,0,1.4,158,...,0.0,1,0,0,0,45,True,0,1,158
12,Wesley Fofana,DEF,Leicester,1.9,0,0,12,0,3.3,272,...,6.0,1,0,0,0,45,True,0,1,272
13,Gianluca Scamacca,FWD,West Ham,0.3,0,0,1,0,0.7,529,...,0.0,1,0,0,0,70,True,0,1,529
14,Alisson Ramses Becker,GK,Liverpool,5.5,0,0,11,0,0.0,281,...,0.0,1,0,0,0,55,False,0,1,281
15,Che Adams,FWD,Southampton,1.5,0,0,0,0,0.0,411,...,0.0,0,0,0,0,65,False,0,1,411
16,Sam Greenwood,FWD,Leeds,0.5,0,0,4,0,0.5,237,...,21.0,1,0,0,0,45,True,0,1,237
17,Nathaniel Chalobah,MID,Fulham,0.0,0,0,0,0,0.0,203,...,0.0,0,0,0,0,45,True,0,1,203
18,Nathaniel Phillips,DEF,Liverpool,2.5,0,0,0,0,0.0,501,...,0.0,0,0,0,0,40,False,0,1,501
19,Loïc Mbe Soh,DEF,Nott'm Forest,1.4,0,0,0,0,0.0,393,...,0.0,0,0,0,0,45,False,0,1,393

In [421]:
df['id']

0         78
1        435
2         60
3        483
4        512
        ...
24415    483
24416    220
24417    676
24418    204
24419    570
Name: id, Length: 24420, dtype: int64

In [402]:
first_name = []
second_name = []
id_list = []
for x in name_list:
    first_name.append(x.split('_')[0])
    second_name.append(x.split('_')[1])
    id_list.append(int(x.split('_')[2]))

In [403]:
name = []
for x in range(0,len(first_name)):
    name.append(f"{first_name[x]}_{second_name[x]}")
len(name)
id_list

[402,
 83,
 199,
 14,
 145,
 205,
 390,
 189,
 471,
 500,
 250,
 386,
 29,
 170,
 382,
 231,
 399,
 20,
 240,
 480,
 153,
 22,
 295,
 15,
 328,
 248,
 206,
 89,
 487,
 476,
 468,
 485,
 299,
 119,
 481,
 247,
 35,
 395,
 453,
 149,
 508,
 512,
 478,
 418,
 403,
 452,
 55,
 301,
 103,
 118,
 288,
 102,
 410,
 25,
 96,
 85,
 80,
 159,
 293,
 24,
 268,
 326,
 148,
 365,
 424,
 174,
 219,
 267,
 356,
 445,
 491,
 190,
 70,
 57,
 276,
 440,
 507,
 2,
 110,
 438,
 278,
 436,
 92,
 50,
 515,
 131,
 101,
 43,
 9,
 518,
 177,
 123,
 316,
 348,
 28,
 74,
 412,
 320,
 152,
 364,
 216,
 380,
 192,
 193,
 284,
 87,
 311,
 261,
 209,
 444,
 430,
 376,
 163,
 460,
 332,
 113,
 290,
 56,
 226,
 128,
 472,
 266,
 428,
 258,
 354,
 217,
 105,
 457,
 21,
 204,
 37,
 381,
 99,
 120,
 42,
 179,
 282,
 116,
 271,
 359,
 171,
 60,
 310,
 406,
 239,
 225,
 181,
 473,
 432,
 517,
 175,
 259,
 325,
 122,
 260,
 416,
 214,
 212,
 41,
 121,
 291,
 361,
 461,
 363,
 130,
 389,
 53,
 269,
 482,
 255,
 464,
 474,
 516,
 465,
 371,
 272,
 501,
 197,
 314,
 66,
 186,
 232,
 383,
 329,
 304,
 281,
 114,
 109,
 51,
 497,
 252,
 394,
 62,
 17,
 467,
 97,
 350,
 172,
 230,
 33,
 372,
 220,
 368,
 18,
 367,
 373,
 351,
 4,
 435,
 521,
 168,
 274,
 323,
 514,
 524,
 409,
 434,
 82,
 32,
 333,
 447,
 321,
 144,
 312,
 233,
 147,
 166,
 254,
 72,
 138,
 338,
 234,
 463,
 335,
 355,
 442,
 146,
 439,
 419,
 315,
 456,
 494,
 141,
 78,
 46,
 398,
 300,
 243,
 441,
 94,
 510,
 490,
 98,
 76,
 421,
 262,
 522,
 191,
 483,
 201,
 81,
 161,
 318,
 222,
 505,
 249,
 420,
 154,
 38,
 459,
 327,
 242,
 45,
 342,
 106,
 294,
 61,
 378,
 475,
 297,
 136,
 208,
 36,
 65,
 308,
 213,
 236,
 107,
 446,
 498,
 273,
 73,
 183,
 469,
 357,
 10,
 525,
 358,
 265,
 210,
 3,
 519,
 520,
 95,
 156,
 54,
 275,
 39,
 48,
 238,
 104,
 484,
 502,
 370,
 450,
 513,
 400,
 150,
 523,
 286,
 44,
 155,
 143,
 349,
 414,
 115,
 287,
 178,
 305,
 224,
 385,
 34,
 344,
 417,
 52,
 411,
 298,
 309,
 140,
 503,
 384,
 160,
 495,
 499,
 47,
 195,
 289,
 451,
 93,
 69,
 229,
 425,
 317,
 479,
 455,
 486,
 331,
 13,
 162,
 415,
 352,
 379,
 322,
 319,
 16,
 346,
 253,
 448,
 167,
 362,
 369,
 126,
 256,
 5,
 86,
 387,
 241,
 100,
 31,
 343,
 187,
 88,
 296,
 68,
 264,
 173,
 279,
 133,
 108,
 339,
 176,
 405,
 443,
 59,
 142,
 313,
 302,
 413,
 125,
 1,
 202,
 75,
 277,
 158,
 285,
 23,
 340,
 374,
 492,
 449,
 244,
 270,
 200,
 207,
 437,
 407,
 19,
 221,
 393,
 223,
 79,
 458,
 257,
 391,
 307,
 489,
 6,
 429,
 426,
 306,
 127,
 132,
 188,
 454,
 427,
 330,
 40,
 408,
 184,
 433,
 431,
 251,
 493,
 64,
 404,
 334,
 84,
 470,
 139,
 196,
 303,
 8,
 157,
 90,
 377,
 360,
 280,
 509,
 283,
 49,
 347,
 235,
 7,
 26,
 237,
 341,
 12,
 58,
 91,
 397,
 185,
 11,
 71,
 337,
 77,
 27,
 211,
 345,
 477,
 324,
 496,
 198,
 164,
 111,
 129,
 511,
 180,
 353,
 63,
 194,
 182,
 388,
 169,
 67,
 203,
 245,
 396,
 30,
 137,
 228,
 292,
 117,
 366,
 263,
 246,
 504,
 135,
 336,
 215,
 227,
 151,
 124,
 423,
 112,
 392,
 422,
 401,
 462,
 165,
 506,
 218,
 488,
 375,
 466,
 134,
 402,
 83,
 199,
 14,
 145,
 205,
 390,
 189,
 471,
 500,
 250,
 386,
 29,
 170,
 382,
 231,
 399,
 20,
 240,
 480,
 153,
 22,
 295,
 15,
 328,
 248,
 206,
 89,
 487,
 476,
 468,
 485,
 299,
 119,
 481,
 247,
 35,
 395,
 453,
 149,
 508,
 512,
 478,
 418,
 403,
 452,
 55,
 301,
 103,
 118,
 288,
 102,
 410,
 25,
 96,
 85,
 80,
 159,
 293,
 24,
 268,
 326,
 148,
 365,
 424,
 174,
 219,
 267,
 356,
 445,
 491,
 190,
 70,
 57,
 276,
 440,
 507,
 2,
 110,
 438,
 278,
 436,
 92,
 50,
 515,
 131,
 101,
 43,
 9,
 518,
 177,
 123,
 316,
 348,
 28,
 74,
 412,
 320,
 152,
 364,
 216,
 380,
 192,
 193,
 284,
 87,
 311,
 261,
 209,
 444,
 430,
 376,
 163,
 460,
 332,
 113,
 290,
 56,
 226,
 128,
 472,
 266,
 428,
 258,
 354,
 217,
 105,
 457,
 21,
 204,
 37,
 381,
 99,
 120,
 42,
 179,
 282,
 116,
 271,
 359,
 171,
 60,
 310,
 406,
 239,
 225,
 181,
 473,
 432,
 517,
 175,
 259,
 325,
 122,
 260,
 416,
 214,
 212,
 41,
 121,
 291,
 361,
 461,
 363,
 130,
 389,
 53,
 269,
 482,
 255,
 464,
 474,
 516,
 465,
 371,
 272,
 501,
 197,
 314,
 66,
 186,
 232,
 383,
 329,
 304,
 281,
 114,
 109,
 51,
 497,
 252,
 394,
 62,
 17,
 467,
 97,
 350,
 172,
 230,
 33,
 372,
 220,
 368,
 18,
 367,
 373,
 351,
 4,
 435,
 521,
 168,
 274,
 323,
 514,
 524,
 409,
 434,
 82,
 32,
 333,
 447,
 321,
 144,
 312,
 233,
 147,
 166,
 254,
 72,
 138,
 338,
 234,
 463,
 335,
 355,
 442,
 146,
 439,
 419,
 315,
 456,
 494,
 141,
 78,
 46,
 398,
 300,
 243,
 441,
 94,
 510,
 490,
 98,
 76,
 421,
 262,
 522,
 191,
 483,
 201,
 81,
 161,
 318,
 222,
 505,
 249,
 420,
 154,
 38,
 459,
 327,
 242,
 45,
 342,
 106,
 294,
 61,
 378,
 475,
 297,
 136,
 208,
 36,
 65,
 308,
 213,
 236,
 107,
 446,
 498,
 273,
 73,
 183,
 469,
 357,
 10,
 525,
 526,
 358,
 265,
 210,
 3,
 519,
 520,
 95,
 156,
 54,
 275,
 39,
 48,
 238,
 104,
 484,
 502,
 370,
 450,
 513,
 400,
 150,
 523,
 286,
 44,
 155,
 143,
 349,
 414,
 115,
 287,
 178,
 305,
 224,
 385,
 34,
 344,
 417,
 52,
 411,
 298,
 309,
 140,
 503,
 384,
 160,
 495,
 499,
 47,
 195,
 289,
 451,
 93,
 69,
 229,
 425,
 317,
 479,
 455,
 486,
 331,
 13,
 162,
 415,
 352,
 379,
 322,
 319,
 16,
 346,
 253,
 448,
 167,
 362,
 369,
 126,
 256,
 5,
 86,
 527,
 387,
 241,
 100,
 31,
 343,
 187,
 88,
 296,
 68,
 264,
 173,
 279,
 133,
 108,
 339,
 176,
 405,
 443,
 59,
 142,
 313,
 302,
 413,
 125,
 1,
 202,
 75,
 277,
 158,
 285,
 23,
 340,
 374,
 492,
 449,
 244,
 270,
 200,
 207,
 437,
 407,
 19,
 221,
 393,
 223,
 79,
 458,
 257,
 391,
 307,
 489,
 6,
 429,
 426,
 306,
 127,
 132,
 188,
 454,
 427,
 330,
 40,
 408,
 184,
 433,
 431,
 251,
 493,
 64,
 404,
 334,
 84,
 470,
 139,
 196,
 303,
 8,
 157,
 90,
 377,
 360,
 280,
 509,
 283,
 49,
 347,
 235,
 7,
 26,
 237,
 341,
 12,
 58,
 91,
 397,
 185,
 11,
 71,
 ...]

In [447]:
df.dtypes

name                           object
position                       object
team                           object
xP                            float64
assists                         int64
bonus                           int64
bps                             int64
clean_sheets                    int64
creativity                    float64
element                         int64
expected_assists              float64
expected_goal_involvements    float64
expected_goals                float64
expected_goals_conceded       float64
fixture                         int64
goals_conceded                  int64
goals_scored                    int64
ict_index                     float64
influence                     float64
kickoff_time                   object
minutes                         int64
opponent_team                   int64
own_goals                       int64
penalties_missed                int64
penalties_saved                 int64
red_cards                       int64
round                           int64
saves                           int64
selected                        int64
starts                          int64
team_a_score                    int64
team_h_score                    int64
threat                        float64
total_points                    int64
transfers_balance               int64
transfers_in                    int64
transfers_out                   int64
value                           int64
was_home                         bool
yellow_cards                    int64
GW                              int64
id                              int64
dtype: object

In [405]:
df.drop(columns='name')
df['name'] = name
df['id'] = id_list
df['id']

0        402
1         83
2        199
3         14
4        145
        ...
21785    466
21786    546
21787    541
21788    134
21789    515
Name: id, Length: 21790, dtype: int64

In [445]:
df.to_sql(f"{pl_season2}_fpl",engine, 'fpl', if_exists='replace', index=False)

26581

In [454]:
sql = """
select * from fpl.fbref
"""

In [459]:
new_df = pd.read_sql_query(sql, engine)
new_df.head(100)

,season,Unnamed: 0,Date,kickoff_date,Day,Round,Venue,Result,Squad,Opponent,...,Cmp.3,Att.3,Cmp%.3,xA,KP,1/3,PPA,CrsPA,id,unique
0,2017,0,2017-08-12,None,Sat,Matchweek 1,Away,D 3–3,Liverpool,Watford,...,1.0,1.0,100.0,0.0,0.0,2.0,0.0,0.0,168,1168
1,2017,1,2017-08-19,None,Sat,Matchweek 2,Home,W 1–0,Liverpool,Crystal Palace,...,1.0,2.0,50.0,0.1,1.0,0.0,1.0,0.0,168,1168
2,2017,2,2017-08-27,None,Sun,Matchweek 3,Home,W 4–0,Liverpool,Arsenal,...,1.0,1.0,100.0,0.5,1.0,0.0,1.0,1.0,168,1168
3,2017,3,2017-09-16,None,Sat,Matchweek 5,Home,D 1–1,Liverpool,Burnley,...,1.0,3.0,33.3,0.1,3.0,3.0,1.0,0.0,168,1168
4,2017,4,2017-09-23,None,Sat,Matchweek 6,Away,W 3–2,Liverpool,Leicester City,...,0.0,1.0,0.0,0.0,1.0,1.0,2.0,0.0,168,1168
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,2017,95,2018-05-05,None,Sat,Matchweek 37,Away,W 2–1,Crystal Palace,Stoke City,...,4.0,7.0,57.1,0.0,0.0,2.0,0.0,0.0,25,1025
96,2017,96,2018-05-13,None,Sun,Matchweek 38,Home,W 2–0,Crystal Palace,West Brom,...,3.0,4.0,75.0,0.4,2.0,4.0,2.0,0.0,25,1025
97,2017,97,2017-11-28,None,Tue,Matchweek 14,Away,D 2–2,Newcastle Utd,West Brom,...,2.0,2.0,100.0,0.0,0.0,2.0,1.0,1.0,590,1590
98,2017,98,2017-12-27,None,Wed,Matchweek 20,Home,L 0–1,Newcastle Utd,Manchester City,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,590,1590
99,2017,99,2017-08-26,None,Sat,Matchweek 3,Away,W 2–0,Swansea City,Crystal Palace,...,2.0,3.0,66.7,0.1,1.0,0.0,1.0,1.0,284,1284

In [460]:
new_df.head(94)

,season,Unnamed: 0,Date,kickoff_date,Day,Round,Venue,Result,Squad,Opponent,...,Cmp.3,Att.3,Cmp%.3,xA,KP,1/3,PPA,CrsPA,id,unique
0,2017,0,2017-08-12,None,Sat,Matchweek 1,Away,D 3–3,Liverpool,Watford,...,1.0,1.0,100.0,0.0,0.0,2.0,0.0,0.0,168,1168
1,2017,1,2017-08-19,None,Sat,Matchweek 2,Home,W 1–0,Liverpool,Crystal Palace,...,1.0,2.0,50.0,0.1,1.0,0.0,1.0,0.0,168,1168
2,2017,2,2017-08-27,None,Sun,Matchweek 3,Home,W 4–0,Liverpool,Arsenal,...,1.0,1.0,100.0,0.5,1.0,0.0,1.0,1.0,168,1168
3,2017,3,2017-09-16,None,Sat,Matchweek 5,Home,D 1–1,Liverpool,Burnley,...,1.0,3.0,33.3,0.1,3.0,3.0,1.0,0.0,168,1168
4,2017,4,2017-09-23,None,Sat,Matchweek 6,Away,W 3–2,Liverpool,Leicester City,...,0.0,1.0,0.0,0.0,1.0,1.0,2.0,0.0,168,1168
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
89,2017,89,2018-03-17,None,Sat,Matchweek 31,Away,W 2–0,Crystal Palace,Huddersfield,...,4.0,8.0,50.0,0.1,0.0,4.0,1.0,0.0,25,1025
90,2017,90,2018-03-31,None,Sat,Matchweek 32,Home,L 1–2,Crystal Palace,Liverpool,...,4.0,11.0,36.4,0.0,0.0,7.0,0.0,0.0,25,1025
91,2017,91,2018-04-07,None,Sat,Matchweek 33,Away,D 2–2,Crystal Palace,Bournemouth,...,2.0,6.0,33.3,0.0,0.0,1.0,0.0,0.0,25,1025
92,2017,92,2018-04-14,None,Sat,Matchweek 34,Home,W 3–2,Crystal Palace,Brighton,...,4.0,5.0,80.0,0.0,0.0,0.0,1.0,0.0,25,1025
93,2017,93,2018-04-21,None,Sat,Matchweek 35,Away,D 0–0,Crystal Palace,Watford,...,1.0,2.0,50.0,0.0,1.0,0.0,1.0,0.0,25,1025

In [458]:
new_df['Date'] = pd.to_datetime(new_df['Date'])

ParserError: Unknown string format: Date present at position 92

In [453]:
new_df.to_sql(f"fpl",engine, 'fpl', if_exists='replace', index=False)

143383