In [76]:
import pandas as pd

In [77]:
pl_season = 2019

In [78]:
player_data = pd.read_csv(f'{pl_season}_merge.csv')

In [79]:
player_data

,Unnamed: 0,url_id,tag,fbref_name,key,first_name,second_name,id,full_name,keep
0,270,45963054,Jamie-Vardy,Jamie Richard Vardy,0,Jamie,Vardy,166,Jamie Vardy,True
1,1004,e46012d4,Kevin-De-Bruyne,Kevin De Bruyne,0,Kevin,De Bruyne,215,Kevin De Bruyne,True
2,1667,3bb7b8b4,Ederson,Ederson Moraes,0,Ederson,Santana de Moraes,212,Ederson Santana de Moraes,True
3,2197,5f09991f,Patrick-van-Aanholt,Patrick John Miguel van Aanholt,0,Patrick,van Aanholt,123,Patrick van Aanholt,True
4,3093,774cf58b,Max-Aarons,Maximillian James Aarons,0,Maximillian,Aarons,274,Maximillian Aarons,True
...,...,...,...,...,...,...,...,...,...,...
442,338685,be927d03,Ashley-Young,Ashley Simon Young,0,Ashley,Young,224,Ashley Young,True
443,339593,6813ac34,Pablo-Zabaleta,Pablo Javier Zabaleta Girod,0,Pablo,Zabaleta,379,Pablo Zabaleta,True
444,339869,b2bc3b1f,Wilfried-Zaha,Dazet Wilfried Armel Zaha,0,Wilfried,Zaha,133,Wilfried Zaha,True
445,340756,2d5f03bf,Christoph-Zimmermann,Christoph Zimmermann,0,Christoph,Zimmermann,275,Christoph Zimmermann,True
446,342511,ce4246f5,Kurt-Zouma,Kurt Happy Zouma,0,Kurt,Zouma,459,Kurt Zouma,True

In [80]:
for x in range(0, (len(player_data)-1)):
    gca = pd.read_csv(f"{pl_season}_stats/{player_data['id'][x]}_gca.csv")
    passing = pd.read_csv(f"{pl_season}_stats/{player_data['id'][x]}_passing.csv")
    summary = pd.read_csv(f"{pl_season}_stats/{player_data['id'][x]}_summary.csv")
    passing_merge = passing.drop(columns= ['Unnamed: 0', 'Date', 'Day', 'Venue', 'Result', 'Squad', 'Opponent', 'Start', 'Pos', 'Min', 'Cmp', 'Att', 'Cmp%', 'Att.1', 'Ast', 'xAG', 'PrgP', 'Match Report'])
    gca_merge = gca.drop(columns= ['Unnamed: 0', 'Date', 'Day', 'Venue', 'Result', 'Squad', 'Opponent', 'Start', 'Pos', 'Min', 'SCA', 'Sh', 'GCA', 'Match Report'])
    summary_merge = summary.drop(columns= ['Unnamed: 0', 'Match Report'])
    merge1 = summary_merge.merge(gca_merge, on = 'Round')
    merge2 = merge1.merge(passing_merge, on= 'Round')
    merge2 = merge2.replace('On matchday squad, but did not play', None)
    merge2 = merge2.dropna()
    merge2.to_csv(f"{pl_season}_stats/{player_data['id'][x]}_merge.csv")